name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: asdf
          POSTGRES_PASSWORD: asdf
          POSTGRES_DB: crud_api_rails_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://asdf:asdf@localhost:5432/crud_api_rails_test"
      QUEUE_DATABASE_URL: "postgres://asdf:asdf@localhost:5432/crud_api_rails_queue_test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Create queue database
        run: |
          PGPASSWORD=asdf psql -h localhost -U asdf -d postgres -c "CREATE DATABASE crud_api_rails_queue_test;"

      - name: Run CI pipeline
        run: bin/ci
